name: Crawl Rondônia Laws

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  crawl_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Should match project.requires-python from pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: uv sync --system # Install main dependencies globally

      - name: Install Internet Archive CLI
        run: pip install internetarchive # publisher.py uses this

      - name: Run Rondônia Crawler
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
          PYTHONPATH: ${{ github.workspace }}/src # Add src to PYTHONPATH so modules can be imported
        run: python scripts/run_rondonia_crawler.py
